name: bernardbadion
favicon: null
layout_spectrum: 0.5366497172508389
typography_spectrum: 0.5133310698438436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5628529491368681
  lightness: 0.4792007051873952
  saturation: 0.5335520158987492
  rhythmicContrast: 0.12784923776052892
purpose: []
